// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYSfxZiU4Oz-pUm_TwAUkVYG3MkOQBL8',
    appId: '1:824312990962:web:de616b1b6f6ad1c364946b',
    messagingSenderId: '824312990962',
    projectId: 'scholar-chat-114b8',
    authDomain: 'scholar-chat-114b8.firebaseapp.com',
    storageBucket: 'scholar-chat-114b8.firebasestorage.app',
    measurementId: 'G-BDHK38F052',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5itr1GBGV8291mbV2Jap8B11t6D5MrI',
    appId: '1:824312990962:android:c22df0d06da615f164946b',
    messagingSenderId: '824312990962',
    projectId: 'scholar-chat-114b8',
    storageBucket: 'scholar-chat-114b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCJJwNsbNIwFKF0cY6Wp_tKpCw9PRCasg',
    appId: '1:824312990962:ios:7f98d9b1a23e378a64946b',
    messagingSenderId: '824312990962',
    projectId: 'scholar-chat-114b8',
    storageBucket: 'scholar-chat-114b8.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCJJwNsbNIwFKF0cY6Wp_tKpCw9PRCasg',
    appId: '1:824312990962:ios:7f98d9b1a23e378a64946b',
    messagingSenderId: '824312990962',
    projectId: 'scholar-chat-114b8',
    storageBucket: 'scholar-chat-114b8.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYSfxZiU4Oz-pUm_TwAUkVYG3MkOQBL8',
    appId: '1:824312990962:web:2b80f3c6174c085564946b',
    messagingSenderId: '824312990962',
    projectId: 'scholar-chat-114b8',
    authDomain: 'scholar-chat-114b8.firebaseapp.com',
    storageBucket: 'scholar-chat-114b8.firebasestorage.app',
    measurementId: 'G-674HL5B6YK',
  );
}
